FH.Admin-Web/Models/TenantsType.cs
using System.Collections.Generic;

namespace FH.Admin_Web
{
    public class PreferredTenant
    {
        public static IDictionary<string, string> GetAll()
        {
            IDictionary<string, string> lsttype = new Dictionary<string, string>();
            lsttype.Add("FAM", "Family");
            lsttype.Add("BAC", "Bachelors");
            lsttype.Add("COM", "Company");
            lsttype.Add("ALL", "All");
            return lsttype;
        }
    }
}

FH.Admin-Web/Controllers/TenantController.cs
using FH.Web.Security;
using System.Web.Mvc;
using FH.Admin.Service;
using FH.Admin.Entities;
using FH.Admin_Web.ViewModel;
using System;
using FH.Util;
using Newtonsoft.Json;

namespace FH.Admin_Web.Controllers
{
    [CustomAuthorize]
    public class TenantController : BaseController
    {
        private readonly TenantBL _tenantBL;

        public TenantController()
        {
            _tenantBL = new TenantBL();
        }

        [HttpGet]
        public ActionResult Add(int pid=0)
        {
            AddTenantModel model = new AddTenantModel();
            model.PropertyId = pid;

            TenantDE de = new TenantDE(){ 
                PropertyId = pid,
                CheckInDate = DateTime.Now
            }; 

            model.PGRoomData = _tenantBL.getAvailableRooms(de);

           // model.PropertyId = pid;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(AddTenantModel req)
        {
            if(ModelState.IsValid)
            {
                TenantDE de = new TenantDE() 
                {
                    PropertyId = req.PropertyId,
                    Name = req.Name,
                    Email = req.Email,
                    Mobile = req.Mobile,
                    RoomId = req.RoomId,
                    Occupancy = req.Occupancy,
                    SecurityAmount = req.SecurityAmount,
                    MonthlyRent = req.MonthlyRent,
                    SecurityDeposit=req.SecurityDeposit,
                    CheckInDate = req.CheckInDate,
                    AdminId=Validator.Validation.DecryptToInt(CurrentUser.User.UserId)
                };

                var output=_tenantBL.AddTenant(de);
                if (output.Id > 0)
                    return RedirectToAction("List");
                else
                    ModelState.AddModelError("", output.Message);
            }

            return View(req);
        }

        [HttpPost]
        public ActionResult GetAvailableRooms(TenantDE req)
        {
            TenantDE de = new TenantDE()
            {
                PropertyId = req.PropertyId,
                CheckInDate = req.CheckInDate
            }; 
            var result = _tenantBL.getAvailableRooms(de);
            if (result != null)
            {  
                var result1 = JsonConvert.SerializeObject(result);
                return JsonResultHelper.Success(result1);
            }
            else 
            {
                return JsonResultHelper.Error("Some Error Occer. Please Try Again");
            }
        }

        [HttpGet]
        public ActionResult List(GetAllTenantVM req)
        {
            TenantDE de = new TenantDE()
            {
                TenantId= req.Tid,
                IsActive1 = req.IsActive1,
                PropertyId = req.Pid,
                Mobile=req.Mobile,
                PageNo=req.Page,
                RoomNo = req.RoomNo
            };

            var tenant=_tenantBL.GetAllTenant(de);

            req.TenantList = tenant.TenantList;
            req.Pager = new Pager(tenant.TotalRecord, tenant.PageNo, tenant.PageSize);
            
            return View(req);
        }

        [HttpGet]
        public ActionResult LastMonthRentNotPaid(GetNOTTenantVM req)
        {
            TenantDE de = new TenantDE()
            {
                TenantId = req.Tid,
                PropertyId = req.Pid,
                Mobile = req.Mobile,
                RoomNo = req.RoomNo,
                IsActive = req.IsActive,
            }; 
            var tenant = _tenantBL.gtnotpaid(de);

            foreach (var tenantData in tenant)
            {
                if (tenantData != null)
                {
                    if (tenantData.CheckInDate.Month == tenantData.RentMonth && tenantData.CheckInDate.Year == tenantData.RentYear)
                    {
                        var rentPerDay = tenantData.MonthlyRent > 0 ? tenantData.MonthlyRent / 30 : 0;
                        var fromDate = tenantData.CheckInDate;
                        tenantData.FromDate = fromDate;
                        tenantData.ToDate = new DateTime(fromDate.Year, fromDate.Month, DateTime.DaysInMonth(fromDate.Year, fromDate.Month));

                        int days = (30 - tenantData.FromDate.Day) + 1;
                        //int days = (tenantData.ToDate.Day - tenantData.FromDate.Day)+1;
                        tenantData.RentAmount = Math.Round(rentPerDay * days, 2);
                        if (tenantData.RentAmount < 1) { tenantData.RentAmount = 1; }
                    }
                    else if (tenantData.CheckOutDate.Month == tenantData.RentMonth && tenantData.CheckOutDate.Year == tenantData.RentYear)
                    {
                        var lastDay = new DateTime(tenantData.CheckOutDate.Year, tenantData.CheckOutDate.Month, DateTime.DaysInMonth(tenantData.CheckOutDate.Year, tenantData.CheckOutDate.Month));
                        var rentPerDay = tenantData.MonthlyRent > 0 ? tenantData.MonthlyRent / lastDay.Day : 0;
                        var fromDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);
                        tenantData.FromDate = fromDate;
                        tenantData.ToDate = tenantData.CheckOutDate;
                        int days = tenantData.ToDate.Day;
                        tenantData.RentAmount = Math.Round(rentPerDay * days, 2);
                        if (tenantData.RentAmount < 1) { tenantData.RentAmount = 1; }
                    }
                    else
                    {
                        var fromDate = new DateTime(tenantData.RentYear, tenantData.RentMonth, 1);
                        tenantData.FromDate = fromDate;
                        tenantData.RentAmount = tenantData.MonthlyRent;
                        tenantData.ToDate = fromDate.AddMonths(1).AddDays(-1);
                    }
                } 
            }

            req.TenantList = tenant;

            return View(req);
        }

        [HttpGet]
        public ActionResult PropertyMap(PropertyMapVM req)
        {
            TenantDE de = new TenantDE()
            {
                PropertyId = req.Pid,
                CheckInDate = req.CheckInDate
            };
            var result = _tenantBL.getAvailableRooms(de);
            //var tenant = _tenantBL.GetAllTenant(de);

            req.PGRoomData = result;

            return View(req);
        }

        [HttpGet]
        public ActionResult Edit(int tid)
        {
            TenantDE de = new TenantDE()
            {
               TenantId=tid
            };

            var tenant = _tenantBL.GetTenant(de);

            if (tenant == null)
                return RedirectToAction("List");
            else
            {
                EditTenantModel model = new EditTenantModel()
                {
                    TenantId = tenant.TenantId,
                    Name = tenant.Name,
                    Email = tenant.Email,
                    Mobile = tenant.Mobile,
                    RoomNo = tenant.RoomNo,
                    RoomId = tenant.RoomId,
                    Occupancy = tenant.Occupancy,
                    MonthlyRent = tenant.MonthlyRent,
                    SecurityAmount = tenant.SecurityAmount,
                    SecurityDeposit=tenant.SecurityDepossit,
                    CheckInDate = tenant.CheckInDate,
                    CheckOutDate = tenant.CheckOutDate,
                    IsActive = tenant.IsActive,
                };

                TenantDE de1 = new TenantDE()
                {
                    PropertyId = tenant.PropertyId
                };
                model.PGRoomData = _tenantBL.getAvailableRooms(de1);


                de1.RoomId = tenant.RoomId;
                model.TenantRoom = _tenantBL.getTenantRooms(de1);
                  
                return View(model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditTenantModel req)
        {
            if(ModelState.IsValid)
            {
                TenantDE de = new TenantDE()
                {
                    TenantId = req.TenantId,
                    CheckOutDate = req.CheckOutDate,
                    Name = req.Name,
                    Email = req.Email,
                    Mobile = req.Mobile,
                    RoomNo = req.RoomNo,
                    RoomId = req.RoomId,
                    Occupancy = req.Occupancy,
                    MonthlyRent = req.MonthlyRent,
                    SecurityAmount = req.SecurityAmount,
                    IsActive = req.IsActive,
                    CheckInDate = req.CheckInDate,
                    AdminId = Validator.Validation.DecryptToInt(CurrentUser.User.UserId)
                };

                _tenantBL.Update(de);

                return RedirectToAction("List");
            }

            return View(req);
        }

        [HttpPost]
        public ActionResult CollectPayment(CollectCashData req) {
            TenantDE data = new TenantDE()
            {
                CreatedBy = Validator.Validation.DecryptToInt(CurrentUser.User.UserId),
                Payment = req.rentAmount,
                PaymentType = "RENT",
                StatusMessage = req.Remark,
                TenantId = req.TenantId,
                RentForMonthStartDate = req.rentForMonthStartDate,
                RentForMonthEndDate = req.rentForMonthEndDate,
            };
             
            var result = _tenantBL.CollectPayment(data);
            if (result != null) {
                return JsonResultHelper.Success("Payment Collected");
            }
            else
            {
                return JsonResultHelper.Error("Some Error Occer. Please Try Again");
            }
        }


        [HttpPost]
        public ActionResult CollectSecurity(CollectCashData req)
        {
            TenantDE data = new TenantDE()

FH.Admin-Web/Views/Tenant/Add.cshtml
@using FH.Admin_Web.ViewModel;
@model AddTenantModel
@{
    ViewBag.Title = "Add Tenant";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="wrapper wrapper-content">
    <h3>Add Tenant</h3>
    <div class="ibox float-e-margins">            
        <div class="ibox-content">
            @using (Html.BeginForm("Add", "Tenant", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                @Html.HiddenFor(x => x.PropertyId);
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label><b>Name</b></label>
                        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Name)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label><b>Mobile</b></label>
                        @Html.TextBoxFor(x => x.Mobile, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Mobile)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group" id="roomDetailsDiv">
                        <label><b>Room Number</b></label>
                        <select name="RoomId" class="form-control">
                            <option>Room Number</option>
                            @{
                                var RoomData = Model.PGRoomData;
                            }
                            @if (Model != null && RoomData != null)
                            {
                                foreach (var item in RoomData)
                                {
                                    if (item.Occupancy == 0.5)
                                    {
                                        <option value="@item.PGRoomInventoryId" style="color:green;">@item.RoomNo (Double Sharing)</option>

                                    }
                                    else if (item.Occupancy == 0)
                                    {
                                        <option value="@item.PGRoomInventoryId">@item.RoomNo</option>

                                    }
                                }
                            }
                        </select>
                        @Html.ValidationMessageFor(x => x.RoomId)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label><b>Occupancy</b></label>
                        <select name="Occupancy" class="form-control">
                            <option value="0.5">Double Sharing</option>
                            <option value="1">Private Room</option>
                        </select> 
                        @Html.ValidationMessageFor(x => x.Occupancy)
                    </div>
                </div>
                <div class="col-md-12"> 
                    <div class="form-group">
                        <label><b>Email</b></label>
                        @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Email)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label><b>Monthly Rent Amount</b></label>
                        @Html.TextBoxFor(x => x.MonthlyRent, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.MonthlyRent)
                    </div>
                </div>
 
                <div class="col-md-12">
                    <div class="form-group">
                        <label><b>Security Amount</b></label>
                        @Html.TextBoxFor(x => x.SecurityAmount, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.SecurityAmount)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label><b>Security Deposit</b></label>
                        @Html.TextBoxFor(x => x.SecurityDeposit, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.SecurityDeposit)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label><b>Check-In Date</b></label>
                        @Html.TextBoxFor(x => x.CheckInDate, new { @Value = (Model.CheckInDate == DateTime.MinValue ? "" : Model.CheckInDate.ToString("yyyy-MM-dd")), @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.CheckInDate)
                    </div>
                </div>
                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
            }
        </div>
    </div>
</div>
<script>
    $(function () {
        $('#CheckInDate').datepicker({
            dateFormat: "yy-mm-dd",
        });

        $("#CheckInDate").change(function(){
            var CheckInDate = $("#CheckInDate").val();
            var PropertyId = $("#PropertyId").val();
            $.post('/tenant/GetAvailableRooms', { CheckInDate: CheckInDate, PropertyId: PropertyId }, function (data) {
                var roomDetails = JSON.parse(data.Message);
                console.log(roomDetails);
                var html = '<label><b>Room Number</b></label> <select name = "RoomId" class="form-control"> <option>Room Number</option>';
                for (var i = 0; i < roomDetails.length; i++) {
                    if (roomDetails[i].Occupancy == 0.5) {
                        html += '<option value="' + roomDetails[i].PGRoomInventoryId + '" style="color:green;">' + roomDetails[i].RoomNo +'(Double Sharing)</option>'
                    } else if (roomDetails[i].Occupancy == 0) {
                        html += '<option value="' + roomDetails[i].PGRoomInventoryId + '">' + roomDetails[i].RoomNo + '</option>'
                    }  
                }
                html += '</select>';
                console.log(html);
                $("#roomDetailsDiv").html(html);

            });

        });

    });
</script>

FH.Admin-Web/Views/Tenant/Edit.cshtml
@using FH.Admin_Web.ViewModel;
@model EditTenantModel
@{
    ViewBag.Title = "Edit Tenant";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="wrapper wrapper-content">
    <h3>Add Tenant</h3>
    <div class="ibox float-e-margins">
        <div class="ibox-content"> 
            @using (Html.BeginForm("Edit", "Tenant", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                @Html.HiddenFor(x => x.TenantId);
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label><b>Name</b></label>
                        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Name)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label><b>Mobile</b></label>
                        @Html.TextBoxFor(x => x.Mobile, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Mobile)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label><b>Room Number</b></label>
                        <select name="RoomId" class="form-control">
                            <option>Room Number</option>
                            @{
                                var RoomData = Model.PGRoomData;
                                var TenantRoom = Model.TenantRoom;
                            }
                            @if (Model != null && RoomData != null)
                            {
                                if (TenantRoom != null)
                                { 
                                    if (Model.Occupancy == 0.5)  {
                                        <option value="@TenantRoom.PGRoomInventoryId" style="color:green;" selected="selected">@TenantRoom.RoomNo (Double Sharing)  Current Room </option>
                                    } else if (Model.Occupancy >= 1)  { 
                                        <option value="@TenantRoom.PGRoomInventoryId" selected="selected">@TenantRoom.RoomNo (Private)  Current Room </option>
                                    }
                                }
                                foreach (var item in RoomData)
                                {
                                    if (TenantRoom != null && item.PGRoomInventoryId == TenantRoom.PGRoomInventoryId) {
                                        continue;
                                    }  
                                    if (item.Occupancy == 0.5)  {
                                        <option value="@item.PGRoomInventoryId" style="color:green;">@item.RoomNo (Double Sharing)</option>
                                    }  else if (item.Occupancy == 0)  {
                                        <option value="@item.PGRoomInventoryId">@item.RoomNo</option>
                                    }
                                } 
                            }
                        </select>
                        @Html.ValidationMessageFor(x => x.RoomId)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label><b>Occupancy</b></label>
                        <select name="Occupancy" class="form-control">
                            @if (TenantRoom != null)
                            {
                                if (Model.Occupancy == 0.5)  {
                                    <option value="0.5" selected="selected">Double Sharing</option>
                                    <option value="1">Private Room</option>                                  
                                } else if (Model.Occupancy >= 1)  { 
                                    <option value="0.5">Double Sharing</option>
                                    <option value="1" selected="selected">Private Room</option>
                                } 
                            } else { 
                                <option value="0.5">Double Sharing</option>
                                <option value="1">Private Room</option>                            
                            }
                        </select>
                        @Html.ValidationMessageFor(x => x.Occupancy)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label><b>Email</b></label>
                        @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Email)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label><b>Monthly Rent Amount</b></label>
                        @Html.TextBoxFor(x => x.MonthlyRent, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.MonthlyRent)
                    </div>
                </div>
 
                <div class="col-md-12">
                    <div class="form-group">
                        <label><b>Security Amount</b></label>
                        @Html.TextBoxFor(x => x.SecurityAmount, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.SecurityAmount)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label><b>Check-In Date</b></label>
                        @Html.TextBoxFor(x => x.CheckInDate, new { @Value = (Model.CheckInDate == DateTime.MinValue ? "" : Model.CheckInDate.ToString("yyyy-MM-dd")), @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.CheckInDate)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label><b>Check-Out Date</b></label>
                        @Html.TextBoxFor(x => x.CheckOutDate, new { @Value = (Model.CheckOutDate == null ? "" : Model.CheckOutDate.Value.ToString("yyyy-MM-dd")), @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.CheckOutDate)
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label><b>Enable</b></label>
                        @Html.CheckBoxFor(x => x.IsActive)
                    </div>
                </div>
                <div class="col-md-12">
                    <button type="submit" class="btn btn-primary">Update</button>
                    <a href="/tenant/list" class="lnk lnk-primary">Back To List</a>
                </div>
            </div>
            }
        </div>
    </div>
</div>
<script>
    $(function () {
        $('#CheckInDate,#CheckOutDate').datepicker({
            dateFormat: "yy-mm-dd",
        });
    });
</script>

FH.Admin-Web/Views/Tenant/PropertyMap.cshtml
@using FH.Admin_Web.ViewModel;
@model PropertyMapVM

@{
    ViewBag.Title = "Tenant List";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="wrapper wrapper-content">
    <h3 class="text-center">Property Map</h3>
  
        <div class="ibox float-e-margins">
            <div class="ibox-content">
                <div class="row">
                    @if (Model != null && Model.PGRoomData != null)
                    {
                        foreach (var item in Model.PGRoomData)
                        {
                            <div class="col-xs-2 col-sm-1" style="    background-color: #ebebebe0;  border: 1px solid #cececec4;">
                                <div class="row">
                                    <div class="col-xs-12"> 
                                        <h5 class="text-center"> @item.RoomNo </h5>
                                    </div>
                                </div>
                                @if(item.Occupancy == 0.5){
                                    <div class="row">
                                        <div class="col-xs-6 col-sm-6" style="height: 10px;  background-color: green; padding-left: 10px;"> </div>
                                        <div class="col-xs-6 col-sm-6" style="height: 10px;  background-color: #fff; padding-right: 10px;"> </div>
                                    </div>                                    
                                } else if(item.Occupancy == 1) {
                                    if (item.Person == 1) { 
                                        <div class="row">
                                            <div class="col-xs-12 col-sm-12" style="height: 10px;  background-color: green;  padding-left: 10px;"></div>
                                        </div>                                                                         
                                    } else { 
                                        <div class="row">
                                            <div class="col-xs-6 col-sm-6" style="height: 10px;  background-color: green;  padding-left: 10px; border-right:1px solid #cececec4;"></div>
                                            <div class="col-xs-6 col-sm-6" style="height: 10px;  background-color: green; padding-right: 10px;"></div>
                                        </div>                                     
                                    }
                                } else if(item.Occupancy == 0) { 
                                    <div class="row">
                                        <div class="col-xs-6 col-sm-6" style="height: 10px;  background-color: #fff;  padding-left: 10px; border-right:1px solid #cececec4;"> </div>
                                        <div class="col-xs-6 col-sm-6" style="height: 10px;  background-color: #fff; padding-right: 10px;"> </div>
                                    </div>                                   
                                }
                            </div>
                        }
                    }
                </div>
            </div>
        </div> 
    </div>

<script>
    function showPaymentHistory(tenantId) {
        $.get('/tenant/TenantPaymentHistory', { tenantId: tenantId }, function (data) {
            $('#tenantLogModel').remove();
            $('body').append(data);
            $('#tenantLogModel').modal('show');
        });
    }

    function closeModel() {
        $('#tenantLogModel').modal('hide');
    }
</script>