FH.Admin-Web/Models/PropertyType.cs
using System.Collections.Generic;

namespace FH.Admin_Web
{
    public class PropertyType
    {
        public static IDictionary<string, string> GetAll()
        {
            IDictionary<string, string> lstType = new Dictionary<string, string>();
            lstType.Add("Flat", "Flat");
            lstType.Add("Room", "Room");
            lstType.Add("Flatmate", "FlatMate");
            lstType.Add("PG", "PG");
            return lstType;
        }

    }
}

FH.Admin-Web/Controllers/PostController.cs
using System.Web.Mvc;
using System.Linq;
using FH.Admin.Entities;
using FH.Web.Security;
using FH.Validator;
using System;
using System.Globalization;
using System.Collections.Generic;
using FH.Admin.Service;

namespace FH.Admin_Web.Controllers
{    
    [CustomAuthorize]
    public class PostController : Controller
    {
        [HttpGet]
        public ActionResult PG()
        {
            return View();
        }        

        [HttpPost]
        public ActionResult PG(PropertyPG property)
        {
            /****************PG Room Detail*************/
            if(property.RoomRentalDetail == null || property.RoomRentalDetail.Count() <= 0)
                return ValidationError("Rental detail required.");

            foreach (var room in property.RoomRentalDetail)
            {
                if (!string.IsNullOrEmpty(room.RoomType) && room.RoomType.ToLower() != "single" && room.RoomType.ToLower() != "double" && room.RoomType.ToLower() != "three" && room.RoomType.ToLower() != "four")
                    return ValidationError("Invalid room type.");

                if (room.ExpectedRent <= 0 || room.ExpectedDeposit <= 0 || room.ExpectedRent > room.ExpectedDeposit)
                    return ValidationError("Expected rent can't be more than deposit.");
            }

            if (property.RoomAmenities != null)
            {
                foreach (var roomAmenity in property.RoomAmenities)
                {
                    if (!Validation.IsInt(roomAmenity.AmenityId))
                        return ValidationError("Invalid room amenities.");
                }
            }

            /*********** Locality Detail ***********/            

            if (string.IsNullOrWhiteSpace(property.PropertyMaster.City))
                return ValidationError("City required.");
            if (!City.GetAll().ContainsKey(property.PropertyMaster.City))
                return ValidationError("Invalid city.");

            if (string.IsNullOrEmpty(property.PropertyMaster.Locality))
                return ValidationError("Locality required.");
            if (property.PropertyMaster.Locality.Length > 100)
                return ValidationError("Locality can't be more than 100 characters.");

            if (string.IsNullOrEmpty(property.PropertyMaster.Latitude) || string.IsNullOrEmpty(property.PropertyMaster.Latitude))
                return ValidationError("Please select locality from list.");

            if (!string.IsNullOrWhiteSpace(property.PropertyMaster.Street) && property.PropertyMaster.Street.Length > 100)
                return ValidationError("Address can't be more than 100 characters.");

            /**************** PG Detail ****************/
            if (string.IsNullOrEmpty(property.PgDetail.TenantGender))
                return ValidationError("PG available for required.");
            else if (property.PgDetail.TenantGender.ToLower() != "male" && property.PgDetail.TenantGender.ToLower() != "female" && property.PgDetail.TenantGender.ToLower() != "any")
                return ValidationError("Invalid PG available for type.");

            if (!string.IsNullOrEmpty(property.PgDetail.PreferredGuest) && !PreferredGuest.GetAll().ContainsKey(property.PgDetail.PreferredGuest))
                return ValidationError("Invalid preferred guest.");

            if (!string.IsNullOrEmpty(property.PgDetail.AvailableFrom))
            {
                string availableFrom = property.PgDetail.AvailableFrom;
                DateTime outAvailableFrom;
                if (DateTime.TryParseExact(availableFrom, "dd-MM-yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out outAvailableFrom))
                {
                    property.PgDetail.AvailableFrom = DateTime.ParseExact(availableFrom, "dd-MM-yyyy", CultureInfo.InvariantCulture).ToString("yyyy-MM-dd");
                }
                else
                    return ValidationError("Invalid available from date format.");
            }

            /*************** PG Rules ******************/

            if (property.pgRules != null)
            {
                foreach (var rule in property.pgRules)
                {
                    if (!PGRulesMaster.GetAll().ContainsKey(rule.RuleId))
                        return ValidationError("Invalid PG rules.");
                }
            }

            List<PGRule> pgRules = new List<PGRule>();
            if (property.pgRules != null)
            {
                foreach (var rule in property.pgRules)
                {
                    var item = PGRulesMaster.GetAll().Where(x => x.Key == rule.RuleId).FirstOrDefault();
                    pgRules.Add(new PGRule { RuleId = item.Key, RuleName = item.Value });
                }
            }

            property.pgRules = pgRules;
            property.PgDetail.PreferredGuest = (!string.IsNullOrWhiteSpace(property.PgDetail.PreferredGuest) ? PreferredGuest.GetAll().Where(x => x.Key.ToLower() == property.PgDetail.PreferredGuest.ToLower()).FirstOrDefault().Value : null);
            property.PropertyMaster.CreatedBy = Convert.ToInt32(EncreptDecrpt.Decrypt(CurrentUser.User.UserId));

            using (var uow = new UnitOfWork())
            {
                try
                {
                    //int propertyId = uow.PropertyBL.AddPropertyPG(property);
                    //if (propertyId > 0)
                    //{
                    //    uow.Commit();
                    //    return Json(new { Success = true, Data = RenderRazorViewToString(ControllerContext, "_Congratulation", null) });
                    //}
                    //else
                        return Json(new { Success = false, ErrorMessage = "Something went wrong.Please try again." });
                }
                catch
                {
                    return Json(new { Success = false, ErrorMessage = "Something went wrong.Please try again." });
                }
            }
        }

        private JsonResult ValidationError(string message)
        {
            return Json(new { Success = false, ErrorMessage = message });
        }
    }
}

FH.Admin-Web/Controllers/PropertyController.cs
using System.Web.Mvc;
using FH.Admin.Entities;
using FH.Admin.Service;
using FH.Web.Security;
using FH.Validator;
using System.Collections.Generic;
using FH.Util;
using System.Net;
using System.Linq;
using System;
using System.Web;
using System.IO;
using System.Globalization;
using FH.Admin_Web.ViewModel;

namespace FH.Admin_Web.Controllers
{
    [CustomAuthorize]
    public class PropertyController : BaseController
    {
        [HttpGet]
        public ActionResult Index(int page = 1, string type = "", string status = "", int propertyId = 0, int ownerId = 0, string ownerMobile = "")
        {
            int pageSize = Convert.ToInt16(System.Configuration.ConfigurationManager.AppSettings["TablePageSize"]);
            int totalRecord;
            int pageIndex = page;

            VMPropertyListing vmProperty = new VMPropertyListing();

            using (UnitOfWork uow = new UnitOfWork())
            {

                vmProperty.propertyMaster = uow.PropertyBL.GetAllProperty(pageSize, pageIndex, type, status, propertyId, ownerId, ownerMobile, out totalRecord);
                vmProperty.pager = new Pager(totalRecord, pageIndex, pageSize);
            }
            ViewBag.type = type;
            ViewBag.status = status;
            ViewBag.OwnerId = ownerId == 0 ? "" : ownerId.ToString();
            ViewBag.PropertyId = propertyId == 0 ? "" : propertyId.ToString();
            ViewBag.OwnerMobile = ownerMobile;

            return View(vmProperty);
        }

        [HttpGet]
        public ActionResult Edit(string pid)
        {
            using (var uow = new UnitOfWork())
            {
                Property propertyDetail = uow.PropertyBL.GetProperty(Convert.ToInt32(pid));
                if (propertyDetail == null)
                    return PartialView("_Error");
                else
                {
                    //string cityCode = propertyDetail.PropertyFlatRoomFlatmate == null ? propertyDetail.PropertyPG.PropertyMaster.City : propertyDetail.PropertyFlatRoomFlatmate.PropertyMaster.City;
                    //int cityId = uow.CityMasterBL.GetAllCity().Where(x => x.CityCode == cityCode).FirstOrDefault().CityId;
                    // propertyDetail.AreaMaster = uow.CityZoneAreaMappingBL.GetArea(cityId);
                    ViewBag.cityMaster = uow.CityMasterBL.GetAllCity();
                    if (propertyDetail.PropertyFlatRoomFlatmate != null)
                    {
                        return View("Edit", propertyDetail);
                    }
                    else if (propertyDetail.PropertyPG != null)
                    {
                        return View("EditPG", propertyDetail);
                    }
                } 
            }

            return PartialView("_Error");
        }

        [HttpPost]
        [AjaxRequestValidation]
        public ActionResult UpdatePropertyDetail(string pid, string ptype, PropertyDetailFlatRoom property)
        {
            int propertyId = Convert.ToInt32(pid);
            if (propertyId == 0)
                return ValidationMessage("Invalid Input.");

            if (string.IsNullOrWhiteSpace(ptype))
                return ValidationMessage("Invalid Input.");

            string propertyType = ptype.ToUpper();

            if (propertyType != EnPropertyType.Flat.ToString().ToUpper() && propertyType != EnPropertyType.Room.ToString().ToUpper() && propertyType != EnPropertyType.Flatmate.ToString().ToUpper())
                return ValidationMessage("Invalid Property Type.");

            if (!ApartmentType.GetAll().ContainsKey(property.ApartmentType))
                ValidationMessage("Invalid Apartment Type.");

            if ((propertyType == "FLAT" || propertyType == "FLATMATE") && !BHKType.GetAll().ContainsKey(property.BhkType))
                return ValidationMessage("Invalid BHK Type.");

            if ((propertyType == "FLATMATE" || propertyType == "ROOM") && !RoomType.GetAll().ContainsKey(property.RoomType))
                return ValidationMessage("Invalid Room Type.");

            if (propertyType == "FLATMATE" && (property.TenantGender.ToLower() != "male" && property.TenantGender.ToLower() != "female"))
                return ValidationMessage("Invalid Tenant Gender.");

            if (string.IsNullOrEmpty(property.PropertySize) || property.PropertySize.Length > 10)
                return ValidationMessage("Invalid Build Up Area.");

            if (!FacingType.GetAll().ContainsKey(property.Facing))
                return ValidationMessage("Invalid Facing Type.");

            if (!PropertyAgeType.GetAll().ContainsKey(property.PropertyAge))
                return ValidationMessage("Invalid Property Age Type.");

            if (property.FloorNo == null || property.FloorNo <= 0)
                return ValidationMessage("Floor No Should Be Positive Numeric.");

            if (property.TotalFloor == null || property.TotalFloor <= 0)
                return ValidationMessage("Total Floor Should Be Positive Numeric.");

            if (property.FloorNo > property.TotalFloor)
                return ValidationMessage("Floor No Should be Less than Total Floor.");

            if (!WaterSupplyType.GetAll().ContainsKey(property.WaterSupply))
                return ValidationMessage("Invalid Water Supply Type.");

            if (property.GateSecurity != "Yes" && property.GateSecurity != "No")
                return ValidationMessage("Invalid Gate Security Type.");

            property.ApartmentType = ApartmentType.GetAll().Where(x => x.Key == property.ApartmentType).Select(x => x.Value).FirstOrDefault();

            if (propertyType == "FLAT" || propertyType == "FLATMATE")
                property.BhkType = BHKType.GetAll().Where(x => x.Key == property.BhkType).Select(x => x.Value).FirstOrDefault();
            else
                property.BhkType = null;

            if (propertyType == "FLATMATE" || propertyType == "ROOM")
                property.RoomType = RoomType.GetAll().Where(x => x.Key == property.RoomType).Select(x => x.Value).FirstOrDefault();
            else
                property.RoomType = null;

            if (propertyType != "FLATMATE")
                property.TenantGender = null;

            property.Facing = FacingType.GetAll().Where(x => x.Key == property.Facing).Select(x => x.Value).FirstOrDefault();
            property.PropertyAge = PropertyAgeType.GetAll().Where(x => x.Key == property.PropertyAge).Select(x => x.Value).FirstOrDefault();
            property.WaterSupply = WaterSupplyType.GetAll().Where(x => x.Key == property.WaterSupply).Select(x => x.Value).FirstOrDefault();
            using (var uow = new UnitOfWork())
            {
                try
                {
                    string result = uow.PropertyBL.UpdatePropertyDetail(propertyId, Convert.ToInt32(EncreptDecrpt.Decrypt(CurrentUser.User.UserId)), property);
                    if (string.IsNullOrEmpty(result))
                    {
                        uow.Commit();
                        return Json(new { Success = true });
                    }
                    else
                        return Json(new { Success = false, ErrorMessage = result });
                }
                catch
                {
                    return Json(new { Success = false, ErrorMessage = "Something went wrong.Please try again." });
                }
            }
        }

        [HttpPost]
        [AjaxRequestValidation]
        public ActionResult UpdateLocalityDetail(string pid, PropertyMaster property)
        {
            int propertyId = Convert.ToInt32(pid);
            if (propertyId == 0)
                return ValidationMessage("Invalid Property Id.");

            // if (!City.GetAll().ContainsKey(property.City))
            //   return ValidationMessage("Invalid City.");
            if (string.IsNullOrWhiteSpace(property.ContactPersonName))
                return ValidationMessage("Contact person name required.");
            else if (property.ContactPersonName.Length > 50)
                return ValidationMessage("Contact person name can't be more than 50 characters.");

            if (string.IsNullOrWhiteSpace(property.ContactPersonMobile))
                return ValidationMessage("Contact person mobile no required.");
            else if (Validation.MobileNo(property.ContactPersonMobile))
                return ValidationMessage("Invalid contact person mobile no.");

            if (string.IsNullOrEmpty(property.Locality))
                return ValidationMessage("Locality Required.");
            else if (property.Locality.Length > 100)
                return ValidationMessage("Locality should not be greater than 100 characters.");

            if (string.IsNullOrEmpty(property.Latitude) || string.IsNullOrEmpty(property.Latitude))
                return ValidationMessage("Please select Locality from list.");

            if (property.Street.Length > 100)
                return ValidationMessage("Street should not be greater than 100 characters.");

            using (var uow = new UnitOfWork())
            {
                try
                {
                    string result = uow.PropertyBL.UpdateLocalityDetail(propertyId, Convert.ToInt32(EncreptDecrpt.Decrypt(CurrentUser.User.UserId)), property);
                    if (string.IsNullOrEmpty(result))
                    {
                        uow.Commit();
                        return Json(new { Success = true });
                    }
                    else
                        return Json(new { Success = false, ErrorMessage = result });
                }
                catch
                {
                    return Json(new { Success = false, ErrorMessage = "Something went wrong.Please try again." });
                }
            }
        }

        [HttpPost]
        [AjaxRequestValidation]
        public ActionResult UpdateRentalDetail(string pid, string ptype, PropertyDetailFlatRoom property)
        {

FH.Admin-Web/Views/Property/AddOffer.cshtml
@using FH.Admin_Web
@model AddOffer

@{
    ViewBag.Title = "Add Offer";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="wrapper wrapper-content">
    <h2>Add Offer</h2>
    <div class="ibox-content">
        <form action="/property/addoffer" method="post">
            @Html.AntiForgeryToken()
            @Html.HiddenFor(x=>x.PropertyId)
            <div class="form-group">
                <label>Title</label>
                @Html.TextBoxFor(x => x.Title, new {@class="form-control",Value=Model.Title })
                @Html.ValidationMessageFor(x=>x.Title)
            </div>
            <div class="form-group">
                @Html.TextBoxFor(x => x.OfferPercent, new {@class="form-control",Value=Model.OfferPercent})
                @Html.ValidationMessageFor(x=>x.OfferPercent)
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
</div>

FH.Admin-Web/Views/Property/_AddAmenity.cshtml
@using FH.Admin.Entities;
@{ 
    var amenityMaster = (IEnumerable<AmenityMaster>)ViewData["amenityMaster"];
}
<div class="col-md-12"><h4 class="text-primary">Provide additional details about your property to get maximum visibilty.</h4></div>
<div class="clearfix"></div><hr>
<h4 class="ml-3">Select the amenities available</h4>
@if (amenityMaster != null)
{
    <div class="row m-0">
        @foreach (var item in amenityMaster)
        {
        <div class="col-md-4 pr-0">
            <div>
                <div class="dv-list-item amenity" data-key="@item.AmenityId">@item.AmenityName</div>
            </div>            
        </div>
        }
    </div>
}
<div class="clearfix"></div><hr>
<div class="text-center">
    <button class="btn btn-secondary" id="btn_amenity_back">Back</button>
    <button id="btn_amenity" class="btn btn-primary">Submit</button>
</div>

FH.Admin-Web/Views/Property/_AddGallery.cshtml
<style>
    .d_none
    {
        display:none !important;
    }
</style>
<div class="col-md-12"><h4 class="text-primary">Upload photo gallery</h4></div>
<div class="clearfix"></div><hr>
<div class="col-md-12">
    <form id="frmFileUpload" action="#" method="POST" enctype="multipart/form-data" class="">
        <input id="fileUpload" type="file" class="d_none" multiple>
        <div class="col-md-12 first-box">
            <div class="upload-images-box" onclick="fileUploader();">
                <img src="~/Content/images/add-more-image.png">
                <div class="clearfix"></div>
                <span class="btn btn-primary mt-4 mb-4">
                    <span>Upload Photos</span>
                </span>
                <ul class="image-instructions">
                    @*<li>Max limit 5 MB per image</li>*@
                    <li>Upload at least 5 photos to increase property quality</li>
                </ul>
            </div>
        </div>
        <ul class="post-property-iamges">
            <li class="d_none">
                <div class="add-more-photos fileinput-button-more" onclick="fileUploader();">
                    <h2>+</h2>
                    <p>Add More Photos</p>
                </div>
            </li>
        </ul>
        <div class="clearfix"></div><br>
        <ul class="image-instructions ins2 d_none">
            @*<li>Max limit 5 MB per image</li>*@
            <li>Upload at least 5 photos to increase property quality</li>
        </ul>
    </form>
    <br>
</div>
<div class="clearfix"></div><hr>
<div class="text-center">
    <button class="btn btn-secondary" id="btn_gallery_back">Back</button>
    <button id="btnGallery" class="btn btn-primary">Submit</button>
</div>

<script>


    @*$('#fileUpload').on('change', uploadFiles);

    function uploadFiles(event)
    {
        if (window.FormData !== undefined) {
            var fileUpload = $("#fileUpload").get(0);
            var files = fileUpload.files;
            $('.first-box').hide();
            $('.add-more-photos').parent().removeClass('d_none');
            $('.ins2').removeClass('d_none');
            for (var i = 0; i < files.length; i++) {
                var l = $('.post-property-iamges li').length - 1;
                $('.post-property-iamges').append('<li class="li'+l+'"><div class="upload-loader"><div class="img-upload-loader"></div></div></li>');
                var formData = new FormData(document.getElementById("frmFileUpload"));
                formData.append(files[i].name, files[i]);
                formData.append("Id",l);
                $.ajax({
                    url: "@Url.Action("UploadGallery", "Property")",
                    type: "POST",
                    cache: false,
                    contentType: false,
                    processData: false,
                    data: formData,
                    success: function (data, status) {
                        if (data.Success == true) {
                            var file = { FilePath: data.Url, FileName: data.File }
                            propertyPost.GalleryDetails.push(file);
                            $('.post-property-iamges .li' + data.Id).css('background', 'url("' + data.Url + '")');
                            $('.post-property-iamges .li' + data.Id + ' .upload-loader').remove();
                            $('.li' + data.Id).append('<span class="remove-picture" data-file="' + data.File + '" data-url="' + data.Url + '"><i class="fa fa-trash"></i></span>');
                        }
                        else
                            $('.post-property-iamges .li'+data.Id).remove();
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        showError("Something went wrong.Please try again.");
                    }
                });
            }
        }
        else {
            showError("This browser is not supported,Please try another.");
        }
    }
      function fileUploader() {
            $('#fileUpload').click();
        }*@
    $('#fileUpload').on('change', uploadFiles);

    function uploadFiles(event)
    {
        if (window.FormData !== undefined) {
            var fileUpload = $("#fileUpload").get(0);
            var files = fileUpload.files;
            $('.first-box').hide();
            $('.add-more-photos').parent().removeClass('d_none');
            $('.ins2').removeClass('d_none');
            for (var i = 0; i < files.length; i++) {
                var l = $('.post-property-iamges li').length - 1;
                $('.post-property-iamges').append('<li class="li'+l+'"><div class="upload-loader"><div class="img-upload-loader"></div></div></li>');
                var formData = new FormData(document.getElementById("frmFileUpload"));
                formData.append(files[i].name, files[i]);
                formData.append("Id",l);
                $.ajax({
                    url: "@Url.Action("UploadGallery", "Property")",
                    type: "POST",
                    cache: false,
                    contentType: false,
                    processData: false,
                    data: formData,
                    success: function (data, status) {
                        debugger;
                        if (data.Success == true) {
                            var file = { FilePath: data.Url,FileName:data.File }
                            propertyPost.GalleryDetails.push(file);
                            $('.post-property-iamges .li' + data.Id).css('background', 'url("' + data.Url + '")');
                            $('.post-property-iamges .li' + data.Id + ' .upload-loader').remove();
                            $('.li' + data.Id).append('<span class="remove-picture" data-file="'+data.File+'" data-url="'+data.Url+'"><i class="fas fa-trash-alt"></i></span>');
                        }
                        else
                            $('.post-property-iamges .li' + data.Id).remove();
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        showError("Something went wrong.Please try again.");
                    }
                });
            }
        }
        else {
            showError("This browser is not supported,Please try another.");
        }
    }
      function fileUploader() {
            $('#fileUpload').click();
        }

</script>

FH.Admin-Web/Views/Property/_AddPGDetail.cshtml
<div class="col-md-12"><h4 class="text-primary">Provide PG/Hostel details</h4></div>
<div class="clearfix"></div><hr>
<div class="col-md-12">
    <div class="form-group">
        <label>Available for</label><br>
                                    <div>
                                        <div class="dv-list-item tenant-gender" data-key="Male">Male</div>
                                        <div class="dv-list-item tenant-gender" data-key="Female">Female</div>
                                        <div class="dv-list-item tenant-gender" data-key="Co-Living">Co-Living</div>
                                        <div class="dv-list-item tenant-gender" data-key="RoomRK">Room/RK</div>
                                    </div>
    </div>
</div>
<div class="col-md-12">
    <div class="form-group">
        <label>Preferred Guests</label>
        <div>
            @foreach (var item in PreferredGuest.GetAll())
            {
                <div class="dv-list-item preferred_tenant" data-key="@item.Key">@item.Value</div>
            }
        </div>
    </div>
</div>
<div class="col-md-12">
    <div class="form-group">
        <label>Available From</label>
        <input type="text" id="avaliable_from" class="form-control" placeholder="dd-mm-yy" value="" autocomplete="off">
    </div>
</div>
<div class="col-md-4">    
                <div class="form-group">
                    <label>Fooding</label><br>
                    <div>
                        <div class="dv-list-item fooding" data-key="true">Yes</div>
                        <div class="dv-list-item fooding" data-key="false">No</div>                        
                    </div>
                </div>
   </div>
<div class="col-md-4">
    <div class="form-group">
        <label>Laundry</label><br>
        <div>
            <div class="dv-list-item laundry" data-key="true">Yes</div>
            <div class="dv-list-item laundry" data-key="false">No</div>
        </div>
    </div>
</div>
<div class="col-md-4">
    <div class="form-group">
        <label>Room Cleaning</label><br>       
            <div class="dv-list-item room-cleaning" data-key="true">Yes</div>
            <div class="dv-list-item room-cleaning" data-key="false">No</div>       
    </div>
</div>
<div class="col-md-12"><h4>PG/Hostel Rules</h4></div>
<div class="row m-0">
    @foreach (var item in PGRulesMaster.GetAll())
    {
        <div class="col-md-4">
            <div class="dv-list-item pg-rule" data-key="@item.Key">@item.Value</div>            
        </div>
    }
</div>
    <div class="clearfix"></div><hr>
    <div class="text-center">
        <button id="btn_pg_back" class="btn btn-secondary">Back</button>
        <button id="btn_pg_detail" class="btn btn-primary">Submit</button>
    </div>

    <script>
        $(function () {
            $('#avaliable_from').datepicker({
                dateFormat: "dd-mm-yy",
            });
        });
    </script>

FH.Admin-Web/Views/Property/_Gallery.cshtml
@using FH.Admin.Entities;
@model IEnumerable<PropertyGalleryDetails>
@{ 
    var galleryUrl = System.Configuration.ConfigurationManager.AppSettings["GalleryFolderPath"];
}
<div class="col-md-12"><h4 class="text-primary">Upload photo gallery</h4></div>
<div class="clearfix"></div><hr>
<div class="col-md-12">
    <div class="container">      
        <form id="frmFileUpload" action="#" method="POST" enctype="multipart/form-data" class="">           
            <div class="row">
                <div class="col-lg-7">                    
                    <span class="btn btn-success fileinput-button">
                        <i class="glyphicon glyphicon-plus"></i>
                        <span>Add files...</span>
                        <input id="fileUpload" type="file">
                    </span>                                         
                </div>                
            </div>            
            <div class="gallery">                
                @if (Model != null)
                {
                    foreach (var item in Model)
                    {
                        <div><img src="@galleryUrl@item.FilePath"/></div>
                    }
                }
            </div>
        </form>
        <br>
    </div>
</div>
<div class="clearfix"></div><hr>
<div class="text-center">
    <button class="btn btn-default" onclick='previousTab("Gallery")'>Back</button>
    <button id="btnSaveGallery" class="btn btn-primary">Save & Continue</button>
    <button class="btn btn-default" onclick='nextTab("Gallery")'>Next</button>
</div>

<script>

    $('#Gallery').on("click", "#btnSaveGallery", function (e) {       
        $('.postPropertyStepBtn a[href="#Amenities"]').tab('show');
    });

    $('#fileUpload').on('change', uploadFiles);

    function uploadFiles(event)
    {     
        if (window.FormData !== undefined) {
            var fileUpload = $("#fileUpload").get(0);
            var files = fileUpload.files;

            var formData = new FormData(document.getElementById("frmFileUpload"));
            formData.append("PropertyId", $('#hdnPropertyId').val())
            for (var i = 0; i < files.length; i++) {
                formData.append(files[i].name, files[i]);
            }
           
            waitingDialog.show('Uploading ...');

            $.ajax({
                url: "@Url.Action("UpdateGallery", "Property")",
                type: "POST",
                cache: false,
                contentType: false,
                processData: false,
                data: formData,
                success: function (data, status) {
                    if (data.Success == true) {
                        $('.gallery').append('<div><img src="' +data.Path + '"/></div>');
                    }
                    else
                        alert(data.Error);
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    alert("Something went wrong.Please try again.");
                },
                complete: function () {
                    waitingDialog.hide();
                }
            });
        }
        else
        {
            alert("This browser is not supported,Please try another.");
        }
    }
</script>