FH.Admin-Web/Controllers/VendorController.cs
using System.Web.Mvc;
using FH.Admin.Entities;
using FH.Web.Security;
using FH.Validator;
using FH.Admin.Service;
using FH.Admin_Web.ViewModel;
using System.Linq;

namespace FH.Admin_Web.Controllers
{
    [CustomAuthorize]
    public class VendorController : BaseController
    {
        [HttpGet]
        public ActionResult AgentList()
        {
            using (var uow = new UnitOfWork())
            {
               return View(uow.VendorBL.GetAllAgent());
            }               
        }

        [HttpGet]
        [AjaxRequestValidation]
        public ActionResult getAgentModel(int ownerId)
        {
            if (ownerId>0)
            {
                Agent objAgent = new Agent();
                using (var uow = new UnitOfWork())
                {
                    objAgent=uow.VendorBL.GetAgent(ownerId);                                       
                    return PartialView("_AddEditAgent", objAgent);
                }
            }
            return ValidationError("Something went wrong.");
        }

        [HttpPost]
        [AjaxRequestValidation]
        public JsonResult UpdateAgent(Agent entity)
        {            
            if (string.IsNullOrEmpty(entity.Name)) return ValidationError("Name required.");
            if (entity.Name.Length > 50) return ValidationError("Name,maximum 50 characters allowed.");

            if (Validation.EmailAddress(entity.Email)) return ValidationError("Invalid email.");
            if (Validation.MobileNo(entity.Mobile)) return ValidationError("Invalid mobile no.");
          
            using (var uow = new UnitOfWork())
            {
                uow.VendorBL.UpdateAgent(entity);
                uow.Commit();
                return Json(new { Success = true});
            }
        }
        
        [HttpGet]
        public ActionResult BuyerList()
        {
            using (var uow = new UnitOfWork())
            {
               return View(uow.VendorBL.GetAllBuyer());
            }   
        }


        [HttpGet]
        public ActionResult AccountList()
        {
            using (var uow = new UnitOfWork())
            {
                UserDetails de = new UserDetails();
                return View(uow.VendorBL.AccountList(de));
            }
        }

        [HttpGet]
        public ActionResult AccountDetails(int id = 0)
        {
            if (id > 0)
            {
                UserDetails de = new UserDetails()
                {
                    AccountId = id
                };

                using (var uow = new UnitOfWork())
                {
                    var owner = uow.VendorBL.AccountList(de).FirstOrDefault();
                    if (owner != null && owner.UserId > 0)
                    {
                        return View(owner);
                    }
                }
            }
            return RedirectToAction("AccountList");
        }

        [HttpGet]
        public ActionResult UpdateAccount(int id = 0)
        {
            if (id > 0)
            {
                UserDetails de = new UserDetails()
                { 
                    AccountId = id
                };

                using (var uow = new UnitOfWork())
                {
                    var owner = uow.VendorBL.AccountList(de).FirstOrDefault();
                    if (owner != null && owner.UserId > 0)
                    { 
                        return View(owner);
                    }
                }
            }
            return RedirectToAction("AccountList");
        }

        [HttpPost]
        [AjaxRequestValidation]
        public ActionResult UpdateAccount(AccountList entity)
        {
            if (string.IsNullOrEmpty(entity.PaytmMID)) return ValidationError("MID Required.");
            if (entity.AccountId == 0) return ValidationError("Account Id Required.");

            using (var uow = new UnitOfWork())
            {
                uow.VendorBL.EditAccount(entity);
                uow.Commit();
                return RedirectToAction("AccountList");
            }
        }

        [HttpGet]
        public ActionResult OwnerList(int id=0,string mobile="")
        {
            using (var uow = new UnitOfWork())
            {
                UserDetails de = new UserDetails()
                {
                    UserId=id.ToString(),
                    Mobile=mobile
                };

                return View(uow.VendorBL.GetAllOwner(de));
            }
        }
       
        private JsonResult ValidationError(string msg)
        {
            return Json(new { Success = false, ErrorMessage = msg });
        }

        [HttpGet]
        public ActionResult AddOwner()
        {   
            return View(new AddOwnerModel());
        }

        [HttpPost]       
        public ActionResult AddOwner(AddOwnerModel req)
        {
            if(ModelState.IsValid)
            {
                OwnerDE de = new OwnerDE()
                {
                    Name = req.Name,
                    Email = req.Email,
                    Password = EncreptDecrpt.Encrypt(req.Mobile),
                    Mobile = req.Mobile
                };

                using (var uow = new UnitOfWork())
                {
                    var owner=uow.VendorBL.GetOwner(de);
                    if (owner != null && owner.Count()>0)
                    {
                        if(owner.Any(x=>x.Mobile==req.Mobile))
                            ModelState.AddModelError("", "Mobile no already exist.");
                        if(owner.Any(x=>x.Email == req.Email))
                            ModelState.AddModelError("", "Email id already exist.");
                    }
                    else
                    {
                        uow.VendorBL.AddOwner(de);
                        uow.Commit();
                        return RedirectToAction("OwnerList");
                    }                    
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult EditOwner(int id=0)
        {
            if (id > 0)
            {
                OwnerDE de = new OwnerDE()
                {
                    UserId = id
                };

                using (var uow = new UnitOfWork())
                {
                    var owner = uow.VendorBL.GetOwner(de).FirstOrDefault();
                    if (owner != null && owner.UserId>0)
                    {
                        AddOwnerModel model = new AddOwnerModel()
                        {
                            UserId = owner.UserId,
                            Name = owner.Name,
                            Email = owner.Email,
                            Mobile = owner.Mobile,
                            IsActive = owner.IsActive
                        };

                        return View(model);
                    }
                }
            }
            return RedirectToAction("OwnerList");
        }        

        [HttpPost]
        public ActionResult EditOwner(AddOwnerModel req)
        {
            if (ModelState.IsValid)
            {    
                using (var uow = new UnitOfWork())
                {
                    OwnerDE de = new OwnerDE()
                    {                                              
                        Mobile = req.Mobile,
                        Email=req.Email
                    };
                    
                    var owner = uow.VendorBL.GetOwner(de);
                    if (owner == null)                    
                        ModelState.AddModelError("", "Invalid user.");                    
                    else if (owner.Where(x=>x.UserId != req.UserId).Any(x=>x.Mobile==req.Mobile))                     
                        ModelState.AddModelError("", "Mobile no already exist.");                   
                    else if(!string.IsNullOrEmpty(req.Email) && owner.Where(x => x.UserId != req.UserId).Any(x => x.Email == req.Email))
                        ModelState.AddModelError("", "Email id already exist.");
                    else
                    {
                        OwnerDE deUser = new OwnerDE()
                        {
                            UserId=req.UserId,
                            Name=req.Name,
                            Email=req.Email,
                            Mobile = req.Mobile,
                            IsActive=req.IsActive
                        };
                        uow.VendorBL.UpdateOwner(deUser);
                        uow.Commit();
                        return RedirectToAction("OwnerList");
                    }
                }
            }

            return View();
        }
    }
}

FH.Admin-Web/Views/Vendor/AccountDetails.cshtml
@using FH.Admin_Web.ViewModel
@model FH.Admin.Entities.AccountList
@{
    ViewBag.Title = "Edit Account";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    string ActiveD = "selected";
}

<style>
    .field-validation-error {
        color: red;
    }

    .validation-summary-errors > ul > li {
        list-style: none;
    }
</style>

<div class="row">
    <div class="col-lg-12">
        <div class="wrapper wrapper-content">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h3>Edit Account</h3>
                        </div>
                        <div class="ibox-content">
                            @using (Html.BeginForm("UpdateAccount", "Vendor", FormMethod.Post))
                            {
                                if (ViewData.ModelState.ContainsKey(""))
                                {
                                    <div class="alert alert-danger" role="alert">
                                        @Html.ValidationSummary(true)
                                    </div>
                                }
                                @Html.HiddenFor(model => model.AccountId)

                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Account Id</label>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>@Model.AccountId</label>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Name</label>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>@Model.AccountHolderName</label>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label>MID</label>
                                            @Html.TextBoxFor(x => x.PaytmMID, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(x => x.PaytmMID)
                                        </div>
                                    </div>

                                    <div class="col-md-12">
                                        <div class="form -group">
                                            <label>Is Active</label>
                                            <select class="form-control" id="IsActive" name="IsActive">
                                                <option value="1" @if (Model.IsActive == 1) { @ActiveD }>Approve</option>
                                                <option value="2" @if (Model.IsActive == 2) { @ActiveD }>Reject</option>
                                                <option value="3" @if (Model.IsActive == 3) { @ActiveD }>Document Pending</option>
                                                <option value="0" @if (Model.IsActive == 0) { @ActiveD }>Pending</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary">Submit</button>
                                            <a href="/vendor/AccountList" class="lnk">Back to Account List</a>
                                        </div>
                                    </div>

                                    <div class="col-md-12">
                                        <div class="form-group">
                                            @{
                                                string[] filePaths = !string.IsNullOrEmpty(Model.FilePath) ? Model.FilePath.Split(',') : new string[0];
                                                for (int i = 0; i < filePaths.Length; i++)
                                                {
                                                    filePaths[i] = filePaths[i].Trim();
                                                }
                                            }
                                            @foreach (var path in filePaths)
                                            {
                                                <img src="@path" alt="Account Image" width="350" height="150" />

                                            }
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

FH.Admin-Web/Views/Vendor/AddOwner.cshtml
@using FH.Admin_Web.ViewModel
@model AddOwnerModel

@{
    ViewBag.Title = "Add Owner";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    .field-validation-error{
        color:red;
    }

    .validation-summary-errors>ul>li{
        list-style:none;
    }
</style>
<div class="row">
    <div class="col-lg-12">
        <div class="wrapper wrapper-content">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h3>Add New Owner</h3>
                        </div>
                        <div class="ibox-content">
                            @using (Html.BeginForm("AddOwner", "Vendor", FormMethod.Post))
                            {
                                if(ViewData.ModelState.ContainsKey(""))
                                {
                                 <div class="alert alert-danger" role="alert">
                                @Html.ValidationSummary(true)
                                 </div>
                                }
                                @Html.HiddenFor(model=>model.UserId)

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label>Name</label>
                                            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(x => x.Name)
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label>Email</label>
                                            @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(x => x.Email)
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label>Mobile</label>
                                            @Html.TextBoxFor(x => x.Mobile, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(x => x.Mobile)
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <button type="submit" class="btn btn-primary">Submit</button>                                            
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

FH.Admin-Web/Views/Vendor/BuyerList.cshtml
@using FH.Admin.Entities;
@model IEnumerable<AgentList>
@{
    ViewBag.Title = "Buyer List";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="wrapper wrapper-content">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5>Buyer List</h5>
                        </div>
                        <div class="ibox-content">
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>
                                                Buyer Name
                                            </th>
                                            <th>
                                                Email Id
                                            </th>
                                            <th>
                                                Mobile
                                            </th>
                                            <th>
                                                Created On
                                            </th>
                                            <th>
                                                Status
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @item.Name
                                                </td>
                                                <td>
                                                    @item.Email
                                                </td>
                                                <td>
                                                    @item.Mobile
                                                </td>
                                                <td>
                                                    @item.CreatedOn.ToString("dd MMM yyyy")
                                                </td>
                                                <td>
                                                    @if (item.IsActive)
                                                    {<button class="btn btn-success btn-xs pointer-events-none">
                                                        Active
                                                    </button>
                                                    }
                                                    else
                                                    {
                                                        <button class="btn btn-warning btn-xs pointer-events-none">
                                                            Disable
                                                        </button>
                                                    }
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

FH.Admin-Web/Views/Vendor/EditOwner.cshtml
@using FH.Admin_Web.ViewModel
@model AddOwnerModel
@{
    ViewBag.Title = "Edit Owner";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    .field-validation-error {
        color: red;
    }

    .validation-summary-errors > ul > li {
        list-style: none;
    }
</style>

<div class="row">
    <div class="col-lg-12">
        <div class="wrapper wrapper-content">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h3>Add New Owner</h3>
                        </div>
                        <div class="ibox-content">
                            @using (Html.BeginForm("EditOwner", "Vendor", FormMethod.Post))
                            {
                                if (ViewData.ModelState.ContainsKey(""))
                                {
                                    <div class="alert alert-danger" role="alert">
                                        @Html.ValidationSummary(true)
                                    </div>
                                }
                                @Html.HiddenFor(model => model.UserId)

                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>Name</label>
                                                @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(x => x.Name)
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>Email</label>
                                                @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(x => x.Email)
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>Mobile</label>
                                                @Html.TextBoxFor(x => x.Mobile, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(x => x.Mobile)
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>IsActive</label>
                                               @Html.CheckBoxFor(x=>x.IsActive)                                                
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <button type="submit" class="btn btn-primary">Submit</button>
                                                <a href="/vendor/ownerlist" class="lnk">Back to Owner List</a>
                                            </div>
                                        </div>
                                    </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

FH.Admin-Web/Views/Vendor/UpdateAccount.cshtml
@using FH.Admin_Web.ViewModel
@model FH.Admin.Entities.AccountList
@{
    ViewBag.Title = "Edit Account";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    string ActiveD = "selected";
}

<style>
    .field-validation-error {
        color: red;
    }

    .validation-summary-errors > ul > li {
        list-style: none;
    }
</style>

<div class="row">
    <div class="col-lg-12">
        <div class="wrapper wrapper-content">
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h3>Edit Account</h3>
                        </div>
                        <div class="ibox-content">
                            @using (Html.BeginForm("UpdateAccount", "Vendor", FormMethod.Post))
                            {
                                if (ViewData.ModelState.ContainsKey(""))
                                {
                                    <div class="alert alert-danger" role="alert">
                                        @Html.ValidationSummary(true)
                                    </div>
                                }
                                @Html.HiddenFor(model => model.AccountId)

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Account Id</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>@Model.AccountId</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Name</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>@Model.AccountHolderName</label>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>MID</label>
                                    @Html.TextBoxFor(x => x.PaytmMID, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(x => x.PaytmMID)
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div class="form -group">
                                    <label>Is Active</label>
                                    <select class="form-control" id="IsActive" name="IsActive">
                                        <option value="1" @if (Model.IsActive == 1) { @ActiveD }>Approve</option>
                                        <option value="2" @if (Model.IsActive == 2) { @ActiveD }>Reject</option>
                                        <option value="3" @if (Model.IsActive == 3) { @ActiveD }>Document Pending</option>
                                        <option value="0" @if (Model.IsActive == 0) { @ActiveD }>Pending</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group" style="margin-top: 10px;">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href="/vendor/AccountList" class="lnk">Back to Account List</a>
                                </div>
                            </div>

                            <div class="col-md-12">
                                <div class="form-group">
                                    <div class="row">
                                        @{
                                            string[] filePaths = !string.IsNullOrEmpty(Model.FilePath) ? Model.FilePath.Split(',') : new string[0];
                                            for (int i = 0; i < filePaths.Length; i++)
                                            {
                                                filePaths[i] = filePaths[i].Trim();
                                            }
                                        }
                                        @foreach (var path in filePaths)
                                        {

                                            var name = path.Split('.');
                                            var name1 = path.Split('/');

                                            var type = name[name.Count() - 1];
                                            var type1 = name1[name1.Count() - 1];
                                            <div class="col-sm-3 col-6">
                                                @if (type == "pdf")
                                                {
                                                    <p> <a class="btn btn-primary" target="_blank" href="@path" download><i class="fa fa-download" aria-hidden="true"></i></a> @type1</p>                                                    
                                                }
                                                else 
                                                {
                                                    <img src="@path" alt="Accountdd Image" filetype="@type" style="width:100%" />
                                                    <a class="btn btn-primary" target="_blank" href="@path" style=" position: absolute; left: 15px;" download="@type1"><i class="fa fa-download" aria-hidden="true"></i> </a>
                                                }
                                            </div>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                                        }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>