FH.Admin-Web/Controllers/SEOController.cs
using FH.Web.Security;
using System.Web.Mvc;
using FH.Admin.Entities;
using FH.Admin.Service;
using FH.Admin_Web.ViewModel;
using FH.Util;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Net;

namespace FH.Admin_Web.Controllers
{
    [CustomAuthorize]
    public class SEOController : BaseController
    {
        private readonly SEOBL _seoBL;

        public SEOController()
        {
            _seoBL = new SEOBL();
        }

        [HttpGet]
        public ActionResult Category()
        {
            return View();
        }

        [HttpGet]
        public PartialViewResult ListCategory(int pageSize, string category ="",int pageNo = 1)
        {
            SEODE de = new SEODE()
            {
                PageSize= pageSize,
                PageNo=pageNo,
                Category=category
            };

            var data= _seoBL.GetAllCategory(de);
            data.Category = category;
            return PartialView("_ListCategory", data);
        }

        [HttpGet]
        public ActionResult AddCategory()
        {
            return View(new AddSEOCategory());
        }

        [HttpPost]
        [AjaxRequestValidation]
        public JsonResult AddCategory(AddSEOCategory model)
        {
            if (string.IsNullOrEmpty(model.Lat))
                return JsonResultHelper.Error("Lat required");
            if (string.IsNullOrEmpty(model.Lng))
                return JsonResultHelper.Error("Lng required");
            if (string.IsNullOrEmpty(model.City))
                return JsonResultHelper.Error("city required");
            if(string.IsNullOrEmpty(model.PropertyType))
                return JsonResultHelper.Error("property type required");
            if (string.IsNullOrEmpty(model.Prefix))
                return JsonResultHelper.Error("prefix required");

            if (model.Radius <= 0)
                return JsonResultHelper.Error("Radius required Interger only.");

            List<SEOCategory> lstCategory = new List<SEOCategory>();

            var lstLocality=_seoBL.GetLocalityByLatLng(model.Lat, model.Lng,model.Radius);

            foreach(var l in lstLocality)
            {
                var objseoCategory = _seoBL.GenerateCategory(l.Locality, model.PropertyType, model.Prefix,l.Lat,l.Lng);
                lstCategory.Add(objseoCategory);
            }

            // string googleResponse = string.Empty;
            //    string[] types = { "restaurant", "transit_station" };
            //var googleApiKey = System.Configuration.ConfigurationManager.AppSettings["GooglePlaceApiKey"].ToString();

            //foreach (var type in types)
            //    {
            //        var url = $"https://maps.googleapis.com/maps/api/place/nearbysearch/json?location={model.Lat},{model.Lng}&radius=1500&type={type}&key={googleApiKey}";
            //        using (WebClient wc = new WebClient())
            //        {
            //            googleResponse = wc.DownloadString(url);
            //        }

            //        dynamic googleData = Newtonsoft.Json.JsonConvert.DeserializeObject(googleResponse);

            //        dynamic results = googleData.results;
            //        foreach (var item in results)
            //        {

            //            string categoryLocality =item.name +" "+item.vicinity+" "+ model.City;
            //        string lat = item.geometry.location.lat;
            //        string lng = item.geometry.location.lng;
            //            var objseoCategory=_seoBL.GenerateCategory(categoryLocality, model.PropertyType, model.Prefix,lat,lng);

            //            lstCategory.Add(objseoCategory);
            //        }
            //    }

            foreach (var item in lstCategory)
                {
                    SEODE de = new SEODE
                    {
                        Category = item.Category,
                        Url = item.Url,
                        MetaTitle=item.MetaTitle,
                        MetaKeyword=item.MetaKeyword,
                        MetaDesc=item.MetaDesc,
                        MetaJson="",
                        Heading=item.Heading,
                        HeadingContent=item.HeadingContent,
                        PropertyType=item.PropertyType,
                        Prefix=item.Prefix,
                        Lat=item.Lat,
                        Lng=item.Lng,
                        City=model.City,
                        UserId=Validator.Validation.DecryptToInt(CurrentUser.User.UserId)
                    };

                 _seoBL.AddCategory(de);
                }

            return JsonResultHelper.Success("Category added successfully.");            
        }

        [HttpGet]
        public ActionResult EditCategory(int id)
        {
            EditSEOCategory model = new EditSEOCategory();
            if (id>0)
            {
                SEODE de = new SEODE()
                {                   
                    Id=id
                };
                var data=_seoBL.GetCategory(de);
                
                if(data!=null)
                {
                    model.Id = data.Id;
                    model.Category = data.Category;
                    model.Url = data.Url;
                    model.MetaTitle = data.MetaTitle;
                    model.MetaKeyword = data.MetaKeyword;
                    model.MetaDesc = data.MetaDesc;
                    model.MetaJson = data.MetaJson;
                    model.Heading = data.Heading;
                    model.HeadingContent = data.HeadingContent;
                }
            }

            return View("EditCategory",model);
        }
        
        [HttpPost]
        public ActionResult EditCategory(EditSEOCategory req)
        {
            if(ModelState.IsValid)
            {
                SEODE de = new SEODE
                {
                    Id=req.Id,
                    Category=req.Category,
                    Url=req.Category.Replace(" ","-"),
                    MetaTitle=req.MetaTitle,
                    MetaDesc=req.MetaDesc,
                    MetaKeyword=req.MetaKeyword,
                    MetaJson=req.MetaJson,
                    Heading=req.Heading,
                    HeadingContent=req.HeadingContent
                };

                string result=_seoBL.UdpateCategory(de);
                req.Result = result;
                req.IsPostBack =true;
            }

            return View(req);
        }

        [HttpPost]
        public ActionResult DeleteCategory(int id)
        {
            try
            {
                if (id <= 0)
                    return JsonResultHelper.Error("id required.");

                SEODE de = new SEODE()
                {
                    Id = id
                };

                _seoBL.DeleteCategory(de);
                return JsonResultHelper.Success("Category deleted.");
            }
            catch(Exception e)
            {
                return JsonResultHelper.Error(e.Message);
            }
        }

        [HttpPost]
        public JsonResult GetCategoryByName(string name)
        {
            SEODE de = new SEODE()
            {
                Category=name
            };

            try
            {
                var data = _seoBL.GetCategoryByAutoSearch(de);
                return JsonResultHelper.Success("", data.Count() > 0 ? data.Select(x => new { Id = x.Id, Category = x.Category }) : null);
            }
            catch(Exception e)
            {
                return JsonResultHelper.Error(e.Message);
            }           
        }        

        [HttpPost]
        public JsonResult ReplaceCategoryText(ReplaceCategoryText req)
        {
            if (req.Id <= 0)
                return JsonResultHelper.Error("Id required");

            var category=_seoBL.GetCategory(new SEODE { Id = req.Id });

            if (category == null)
                return JsonResultHelper.Error("No data found for category.");
            
                category.Category = category.Category.Replace(req.OldText, req.NewText);
                category.Url = category.Category.Replace(req.OldText, req.NewText).Replace(" ", "-");
                category.MetaTitle = category.MetaTitle.Replace(req.OldText, req.NewText);
                category.MetaKeyword = category.MetaKeyword.Replace(req.OldText, req.NewText);
                category.MetaDesc = category.MetaDesc.Replace(req.OldText, req.NewText);
                category.MetaJson = category.MetaJson.Replace(req.OldText, req.NewText);
                category.Heading = category.Heading.Replace(req.OldText, req.NewText);
                category.HeadingContent = category.HeadingContent.Replace(req.OldText, req.NewText);
            
            SEODE de = new SEODE
            {
                Id = category.Id,
                Category = category.Category,
                Url = category.Url,
                MetaTitle = category.MetaTitle,
                MetaDesc = category.MetaDesc,
                MetaKeyword = category.MetaKeyword,
                MetaJson = category.MetaJson,
                Heading = category.Heading,
                HeadingContent = category.HeadingContent
            };

            string result = _seoBL.UdpateCategory(de);
            if (string.IsNullOrEmpty(result))
                return JsonResultHelper.Success("Update successfully.");
            else
                return JsonResultHelper.Error(result);
        }

        [HttpPost]
        public JsonResult AddLocality(string locality,string lat,string lng,string city,int radius)
        {
            if (string.IsNullOrWhiteSpace(locality))
                return JsonResultHelper.Error("Locality required.");
            if (string.IsNullOrWhiteSpace(lat) || string.IsNullOrWhiteSpace(lng) || string.IsNullOrWhiteSpace(city))
                return JsonResultHelper.Error("Lat Lng City required.");

            if (radius <= 0)

FH.Admin-Web/Views/SEO/AddCategory.cshtml
@using FH.Admin_Web.ViewModel
@model AddSEOCategory

@{
    ViewBag.Title = "Add Category";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="wrapper wrapper-content">
    <div class="row">
        <div class="ibox-title">
            <h3>Add Category</h3>
        </div>
        <div class="ibox float-e-margins">
            <div class="space"></div>
            <div class="ibox-content">
                <form id="frmAddCategory">                  
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-3 pr-0">
                                <div>
                                    <div class="dv-list-item ptype" data-key="pg">PG</div>
                                </div>
                            </div>
                            <div class="col-md-3 pr-0">
                                <div>
                                    <div class="dv-list-item ptype" data-key="flat">FLAT</div>
                                </div>
                            </div>
                            <div class="col-md-3 pr-0">
                                <div>
                                    <div class="dv-list-item ptype" data-key="room">ROOM</div>
                                </div>
                            </div>
                            <div class="col-md-3 pr-0">
                                <div>
                                    <div class="dv-list-item ptype" data-key="flatmate">FLATMATE</div>
                                </div>
                            </div>
                        </div>
                       
                        <div class="col-md-12">
                            <hr />
                        </div>

                        <div class="col-md-12 pg" style="display:none">
                            <div class="col-md-4 pr-0">
                                <div>
                                    <div class="dv-list-item type" data-key="Boys">Boys PG</div>
                                </div>
                            </div>
                            <div class="col-md-4 pr-0">
                                <div>
                                    <div class="dv-list-item type" data-key="Girls">Girls PG</div>
                                </div>
                            </div>
                            <div class="col-md-4 pr-0">
                                <div>
                                    <div class="dv-list-item type" data-key="Co-Living">Co-Living PG</div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-12 flat" style="display:none">
                            <div class="col-md-3 pr-0">
                                <div>
                                    <div class="dv-list-item type" data-key="1 BHK">1BHK FLAT</div>
                                </div>
                            </div>
                            <div class="col-md-3 pr-0">
                                <div>
                                    <div class="dv-list-item type" data-key="2 BHK">2BHK FLAT</div>
                                </div>
                            </div>
                            <div class="col-md-3 pr-0">
                                <div>
                                    <div class="dv-list-item type" data-key="3 BHK">3BHK FLAT</div>
                                </div>
                            </div>
                            <div class="col-md-3 pr-0">
                                <div>
                                    <div class="dv-list-item type" data-key="4 BHK">4BHK FLAT</div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-12 room" style="display:none">
                            <div class="col-md-4 pr-0">
                                <div>
                                    <div class="dv-list-item type" data-key="Private room">Private ROOM</div>
                                </div>
                            </div>
                            <div class="col-md-4 pr-0">
                                <div>
                                    <div class="dv-list-item type" data-key="Shared room">Shared ROOM</div>
                                </div>
                            </div>
                            <div class="col-md-4 pr-0">
                                <div>
                                    <div class="dv-list-item type" data-key="Shared & Private rooms">Both</div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-12 flatmate" style="display:none">
                            <div class="col-md-4 pr-0">
                                <div>
                                    <div class="dv-list-item type" data-key="male">Male Flatmate</div>
                                </div>
                            </div>
                            <div class="col-md-4 pr-0">
                                <div>
                                    <div class="dv-list-item type" data-key="female">Female Flatmate</div>
                                </div>
                            </div>
                            <div class="col-md-4 pr-0">
                                <div>
                                    <div class="dv-list-item type" data-key="Co-Living">Co-Living Flatmate</div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <hr />
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Locality</label>
                              <input type="text" class="form-control" value="" id="locality" /> 
                                <input type="hidden" id="hdnLat" />
                                <input type="hidden" id="hdnLng" />
                                <input type="hidden" id="hdnCity" />
                            </div>
                        </div>      
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Radius( In Kilometers)</label>
                                <input type="number" class="form-control" id="radius" maxlength="2"/>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <button type="button" class="btn btn-primary" onclick="addCategory()">Submit</button>
                                <a href="/seo/category" class="btn btn-link">Back To List</a>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@Html.Partial("~/Views/Property/_GoogleMapGeoDecode.cshtml")
<script>
    function addCategory() {
        console.log('called.');
        var locality = $('#locality').val();
        var lat = $('#hdnLat').val();
        var lng = $('#hdnLng').val();
        var radius = $('#radius').val();

        if (lat == '' || lng == '') { showError('Locality required.'); return; }

        var ptype = $('.ptype.active').data('key');
        var types = $('.' + ptype + ' .type.active').data('key');
        if (ptype == '' || types == '') { showError("Select property types."); return; }

        if (radius === '') { showError('Radius required.'); return; }

        var data = { Locality: locality, Lat: lat, Lng: lng, PropertyType: ptype, Prefix: types, City: $('#hdnCity').val(), Radius: radius };
        $.post('/seo/addcategory', data, function (res) {
            if (res.Success == true) { redirect('/seo/category', res.Message); }
            else
                showError(res.Message);
        });
    }

    $('.ptype').click(function () {
        $('.ptype').removeClass('active');
        $(this).addClass('active');

        var ptype = $(this).data('key');
        
        $('.flat,.pg,.room,.flatmate').hide();
        $('.' + ptype).show();        

    });

    $('.type').click(function () {
        $('.type').removeClass('active');
        $(this).addClass('active');
    });

</script>

FH.Admin-Web/Views/SEO/AddLocality.cshtml
@{
    ViewBag.Title = "AddLocality";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="wrapper wrapper-content">
    <div class="row">
        <div class="ibox-title">
            <h3>Add Locality</h3>
        </div>
        <div class="ibox float-e-margins">
            <div class="space"></div>
            <div class="ibox-content">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Locality</label>
                            <input type="text" class="form-control" value="" id="locality" />
                            <input type="hidden" id="hdnLat" />
                            <input type="hidden" id="hdnLng" />
                            <input type="hidden" id="hdnCity" />
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Radius( In Meters)</label>
                            <input type="number" id="radius" class="form-control"/>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <button type="button" class="btn btn-default" onclick="addSeoLocality()">Submit</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@Html.Partial("~/Views/Property/_GoogleMapGeoDecode.cshtml")

<script>
    function addSeoLocality() {

        var locality = $('#locality').val();
        var lat = $('#hdnLat').val();
        var lng = $('#hdnLng').val();
        var city = $('#hdnCity').val();
        var radius = $('#radius').val();

        if (locality === '') { showError('Select Locality.'); return;}

        if (lat === '' || lng === '') { showError('Lat Lng required.'); return; }

        if (city === '') { showError('City required.'); return; }

        if (radius === '') { showError('Radius required.'); return; }

        $.post('/seo/addlocality', { locality: locality, city: city, lat: lat, lng: lng, radius: radius }, function (res) {
            if (res.Success == true)
                redirect(res.Data.Url, res.Message);
            else
                showError(res.Message);
        });
    }
</script>

FH.Admin-Web/Views/SEO/Category.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="wrapper wrapper-content">
    <div class="row">        
            <div class="ibox-title">
                <h3>Category</h3>
            </div>
            <div class="ibox float-e-margins">
                <div class="space"></div>
                <div class="ibox-content">
                    <div class="col-md-12" style="padding:0px">                      
                       <div class="col-md-5">
                           <a href="/seo/addCategory" class="btn btn-success">Add Category</a>
                       </div>
                        <div class="col-md-5">
                            <input type="text" id="category" class="form-control" placeholder="Category"/>
                        </div>
                        <div class="col-md-1">
                            <button class="btn btn-info" style="padding:10px" onclick="getCategories()"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                    <div id="lstcategory"></div>
                </div>
            </div>
    </div>
</div>

    <script>

        $(function () {
            getCategories();
        });
        
        function getCategories(page = 1, pageSize = 50) {
            $.get('/seo/listcategory', { category: $('#category').val(), pageNo: page, pageSize: pageSize }, function (res) {
                $('#lstcategory').html(res);
            });            
        }
        
        function paging(page) {
            getCategories(page);
        }

        function deleteCategory(id) {
            $.post('/seo/DeleteCategory', { id: id }, function (res) {
                if (res.Success == true)
                    showSuccessMessage(res.Message);
                else
                    showError(res.Message);
            });

        }
</script>

FH.Admin-Web/Views/SEO/EditLocality.cshtml
@using FH.Admin.Entities
@model SEOLocalityMaster

@{
    ViewBag.Title = "Edit Locality";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="wrapper wrapper-content">
    <div class="row">
        <div class="ibox-title">
            <h3>Add Category</h3>
        </div>
        <div class="ibox float-e-margins">
            <div class="space"></div>
            <div class="ibox-content">               
                    <div class="row">                     
                        <div class="col-md-12">
                            <div class="form-group">
                                @Html.HiddenFor(x => x.Id)
                                @Html.TextBoxFor(x => x.Locality, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <button type="button" class="btn btn-primary" onclick="submit()">Submit</button>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>

<script>
    function submit() {
        $.post('/seo/editlocality', { Id: $('#Id').val(), Locality: $('#Locality').val() }, function (res) {

            if (res.Success === true)
                showSuccessMessage(res.Message);
            else
                showError(res.Message);
        });
    }
</script>

FH.Admin-Web/Views/SEO/ListLocality.cshtml
@using FH.Admin.Entities
@model SEOLocalityVM

@{
    ViewBag.Title = "List Locality";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="wrapper wrapper-content">
    <div class="row">
        <div class="ibox-title">
            <h3>Locality</h3>
        </div>
        <div class="ibox float-e-margins">
            <div class="space"></div>
            <div class="ibox-content">
                <div class="row">
                    @using (Html.BeginForm("ListLocality", "SEO", FormMethod.Get))
                    {
                        <div class="row">
                            <div class="col-md-12" style="padding:0px">
                                <div class="col-md-5">
                                    <a href="/seo/addLocality" class="btn btn-success">Add Locality</a>
                                </div>
                                <div class="col-md-7">
                                    <div class="col-md-10" style="padding-left:0px">
                                        <input type="text" name="searchKey" class="form-control" />
                                    </div>
                                    <div class="col-md-2">
                                        <button type="submit" class="btn btn-success form-control"><i class="fa fa-search"> </i></button>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <table class="table table-bordered" style="font-size:12px">
                                    <thead>
                                        <tr>
                                            <th>
                                                Locality
                                            </th>
                                            <th>
                                                City
                                            </th>
                                            <th>

                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Model != null && Model.ListLocality != null)
                                        {
                                            foreach (var data in Model.ListLocality)
                                            {
                                                <tr>
                                                    <td>
                                                        @data.Locality
                                                    </td>
                                                    <td>
                                                        @data.City
                                                    </td>
                                                    <td>
                                                        <a href="/seo/editlocality?id=@data.Id" target="_blank" class="btn btn-primary"><i class="fa fa-edit"></i></a>
                                                        &nbsp;
                                                        <button type="button" class="btn btn-primary" onclick="deleteLocality(this,@data.Id)">
                                                            <i class="fa fa-remove"></i>
                                                        </button>
                                                    </td>
                                                </tr>
                                            }
                                        }
                                    </tbody>
                                </table>
                                @Html.Partial("_Pager", new Pager(Model.TotalRecord, Model.PageNo, Model.PageSize, pageLoadEnable: true))

                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function deleteLocality(th, id) {         
        var res = confirm("Are you want to delete this locality");
        if (res) {
            $.post("/seo/deletelocality", { Id: id }, function (data) {
                if (data.Success == true) {
                    console.log($(this).closest('tr'));
                    $(th).closest('tr').remove();
                    showSuccessMessage(data.Message);
                }
                else
                    showError(data.Message);
            });
        }
    }
</script>

FH.Admin-Web/Views/SEO/_ListCategory.cshtml
@using FH.Admin.Entities
@model SEOCategoryVM
    
        <table class="table table-bordered" style="font-size:12px">
            <thead>
                <tr>
                    <th>
                        ID
                    </th>
                    <th>
                        Name
                    </th>
                    <th>
                        Meta Title
                    </th>
                    <th>
                        Meta Keyword
                    </th>
                    <th>
                        Meta Description
                    </th>
                    <th>City</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.SEOCategories != null)
                {
                    foreach (var item in Model.SEOCategories)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Url</td>
                            <td>@item.MetaTitle</td>
                            <td>@item.MetaKeyword</td>
                            <td>@item.MetaDesc</td>
                            <td>@item.City</td>
                            <td>
                                <a target="_blank" href="/seo/editcategory/@item.Id" class="btn btn-xs btn-white"><i class="fa fa-edit"></i></a>
                                <button onclick="deleteCategory(@item.Id)" class="btn btn-xs btn-white"><i class="fa fa-remove"></i></button>
                            </td>
                         </tr>
                    }
                }
            </tbody>
        </table>
        @Html.Partial("_Pager", new Pager(Model.TotalRecord, Model.PageNo, Model.PageSize,pageLoadEnable:false))